### ISSUE TITLE
성능 이슈 해결

### ISSUE THREAD

**Issue by Myeongchan-Kim** [Paul-Kim/STACK#27]
아무래도 버텍스버퍼 생성 / 해제 하는데서가 문제인듯...

**Comment by Myeongchan-Kim** [comment]
일단 색깔을 새로 세팅할때마다 플래그를 설정해서
플래그 켜져있을때만 새로 버퍼 만들게 바꿈.

**Comment by kimsin3003** [comment]
Preload 기능 추가.
